config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}
  resources :documents
  get 'tags/:tag', to: 'home#index', as: :tag

  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/document.rb
class Document < ActiveRecord::Base
  mount_uploader :file, FileUploader
  process_in_background :file
  validates :title, :file, presence: true

  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings

  def to_jq_upload
    {
        name: read_attribute(:file),
        size: file.size,
        url: file.url,
        delete_url: "/documents/#{id}",
        delete_type: 'DELETE'
    }
  end

  def self.tagged_with name
    Tag.find_by(name: name).documents
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end if names
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :documents, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :document
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable

  has_many :documents, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  add_breadcrumb 'Главная', :root_path

  def respond_modal_with(*args, &blk)
    options = args.extract_options!
    options[:responder] = ModalResponder
    respond_with *args, options, &blk
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit! }
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :authenticate_user!, except: [:show]
  before_filter :find_document, only: [:show, :destroy]
  add_breadcrumb 'Мои файлы', :documents_path

  respond_to :html, :json

  def index
    @documents = current_user.documents
  end

  def new
    add_breadcrumb 'Загрузить', :new_documents_path
    @document = current_user.documents.new

    respond_to do |format|
      format.html
      format.json { render json: @document }
    end
  end

  def create
    @document = current_user.documents.new(document_params)

    if @document.save
      render json: {file: @document.to_jq_upload, url: documents_path, status: 'success'}, status: :created, location: @document
    else
      render json: @document.errors, status: :unprocessable_entity
    end
  end

  def show
    respond_modal_with @document
  end

  def destroy
    @document.destroy
    redirect_to documents_path, notice: 'Файл успешно удален'
  end

  private

  def document_params
    params.require(:document).permit(:title, :file, :tag_list)
  end

  def find_document
    @document = Document.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @documents = if params[:tag]
      Document.tagged_with(params[:tag])
    else
      Document.all
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    add_breadcrumb 'Регистрация', :new_user_registration_path
    super()
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def new
    add_breadcrumb 'Войти', :new_user_session_path
    super()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, path)
    class_name = 'active' if current_page? path
    content_tag(:li, class: class_name) do
      link_to link_text, path
    end
  end

  def icon(name)
    content_tag(:span, nil, class: "glyphicon glyphicon-#{name}")
  end

  def flash_class(level)
    case level
      when 'notice' then 'success'
      when 'error' then 'danger'
      when 'alert' then 'danger'
    end
  end

  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end

  def file_tag doc, option=nil
    if doc.file_processing?
      image_tag '189x142.gif', class: "img-rounded #{option}"
    elsif doc.file_url.match(/jpeg|png|jpg|gif/)
      image_tag doc.file_url(:thumb), class: "img-rounded #{option}"
    else
      image_tag '189x142.gif', class: "img-rounded #{option}"
    end
  end
end

app/views/documents/_form.html.haml
= simple_form_for @document, html: {multipart: true, id: 'fileupload'} do |f|
  = f.input :title
  = f.input :tag_list
  -#= f.input_field :file
  -#= f.button :submit, 'Сохранить'

  .fileupload-buttonbar
    %span.btn.btn-sm.btn-success.fileinput-button
      %i.glyphicon.glyphicon-plus
      %span Добавить файл
      = f.file_field :file, id: 'upload-field'
    %button.btn.btn-sm.btn-primary.start{type: 'submit'}
      %i.glyphicon.glyphicon-floppy-save
      %span Сохранить
    %span.fileupload-loading
  %table.table.table-striped{role: 'presentation'}
    %tbody.files

/ The template to display files available for upload
%script#template-upload{type: 'text/x-tmpl'}
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  %tr.template-upload.fade
    %td.preview
      %span.fade
    %td.name
      %span {%=file.name%}
    %td.size
      %span {%=o.formatFileSize(file.size)%}
    {% if (file.error) { %}
    %td.error{colspan: '2'}
      %span.label.label-important Ошибка
      {%=locale.fileupload.errors[file.error] || file.error%}
    {% } else if (o.files.valid && !i) { %}
    %td
      .progress
        .progress-bar.progress-bar-success
    %td.start{style: 'display: none'}
      {% if (!o.options.autoUpload) { %}
      %button.btn.btn-sm.btn-primary
        %i.glyphicon.glyphicon-upload
        %span Сохранить
      {% } %}
    {% } else { %}
    %td{colspan: '2'}
    {% } %}
    %td.cancel
      {% if (!i) { %}
      %button.btn.btn-sm.btn-warning
        %i.glyphicon.glyphicon-ban-circle
        %span Отмена
      {% } %}
  {% } %}
/ The template to display files available for download
%script#template-download{type: 'text/x-tmpl'}
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  %tr.template-download.fade
    {% if (file.error) { %}
    %td
    %td.name
      %span {%=file.name%}
    %td.size
      %span {%=o.formatFileSize(file.size)%}
    %td.error{colspan: '2'}
      %span.label.label-important Ошибка
      {%=locale.fileupload.errors[file.error] || file.error%}
    {% } else { %}
    %td.preview
      {% if (file.thumbnail_url) { %}
      %a{download: "{%=file.name%}", href: "{%=file.url%}", rel: 'gallery', title: "{%=file.name%}"}
        %img{src: "{%=file.thumbnail_url%}"}/
      {% } %}
    %td.name
      %a{download: "{%=file.name%}", href: "{%=file.url%}", rel: 'gallery', title: "{%=file.name%}"} {%=file.name%}
    %td.size
      %span {%=o.formatFileSize(file.size)%}
    %td{colspan: '2'}
    {% } %}
    %td.delete
      %button.btn.btn-sm.btn-danger{"data-type" => "{%=file.delete_type%}", "data-url" => "{%=file.delete_url%}"}
        %i.glyphicon.glyphicon-trash
        %span Удалить
      %input{name: 'delete', type: 'checkbox', value: '1'}
  {% } %}

app/views/documents/_profile.html.haml
.well
  %h4 Профиль
  #profile
    %p
      %strong Электронная почта:
    %p
      = current_user.email
    %p
      %strong Кол-во загруж. файлов:
    %p
      = current_user.documents.count
    %p
      %strong Последний раз заходил в:
    %p
      = current_user.last_sign_in_at

app/views/documents/_tags.html.haml
.well
  %h4 Tags
  #tag_cloud
    -tag_cloud Document.tag_counts, %w[s m l] do |tag, css_class|
      = link_to tag.name, tag_path(tag.name), class: css_class

app/views/documents/index.html.haml
.row
  .col-md-9
    .row
      -@documents.each do |f|
        .col-md-3.file-block
          .thumb
            = link_to file_tag(f), document_path(f), data: {modal: true}
          .size
            = number_to_human_size(f.file.file.size)
          .title
            = link_to f.title, document_path(f), data: {modal: true}
  .col-md-3
    = render 'documents/profile'

app/views/documents/new.html.haml
= render 'form'

app/views/documents/show.html.haml
= content_for :title, @document.title.titleize

.modal-body
  %p
    = file_tag @document, 'center-block show-file'
  %p
    = icon('user')
    = @document.user.email
  %p
    = icon('calendar')
    = @document.created_at
  %p
    = icon('floppy-disk')
    = number_to_human_size(@document.file.file.size)
  %p
    = link_to icon('download') + ' Скачать', @document.file_url

.modal-footer
  %button.btn.btn-sm.btn-danger{'data-dismiss' => 'modal', type: 'button'} Закрыть

app/views/home/index.html.haml
.row
  .col-md-9
    .row
      -@documents.each do |f|
        .col-md-3.file-block
          .thumb
            = link_to file_tag(f), document_path(f), data: {modal: true}
          .size
            = number_to_human_size(f.file.file.size)
          .title
            = link_to truncate(f.title, length: 40), document_path(f), data: {modal: true}
  .col-md-3
    = render 'documents/tags'

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top.navbar-inverse{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "#{root_url}"} Loader
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = nav_link icon('home') + ' Главная', root_url
        -if user_signed_in?
          = nav_link icon('list') + ' Мои файлы', documents_path
      %ul.nav.navbar-nav.navbar-right
        -if user_signed_in?
          %li
            = link_to icon('upload') + ' Загрузить', new_document_path
          %li
            = link_to icon('off') + ' Выйти', destroy_user_session_path, data: {method: :delete}, title: 'Выйти'
        -else
          %li
            = link_to icon('log-in') + ' Регистрация', new_user_registration_path, title: 'Регистрация'
          %li
            = link_to icon('log-in') + ' Войти', new_user_session_path, title: 'Войти'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Loader
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta{content: 'width=device-width, initial-scale=1.0', name: 'viewport'}
  %body
    = render 'layouts/header'
    .container
      = render 'shared/breadcrumbs'
      = render 'shared/flash', flash: flash
      = yield
    #modal-holder

app/views/layouts/modal.html.haml
#mainModal.modal{"aria-hidden" => "true", "aria-labelledby" => "mainModalLabel", role: 'dialog', tabindex: '-1'}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", type: "button"}
          %span{"aria-hidden" => "true"} &times;
          %span.sr-only Close
        %h4#mainModalLabel.modal-title
          = yield :title if content_for? :title
          \&nbsp;
      = yield

app/views/shared/_breadcrumbs.html.haml
.row
  .col-md-12
    = render_breadcrumbs builder: BootstrapBreadcrumbsBuilder

app/views/shared/_flash.html.haml
-flash.each do |key, value|
  = content_tag :div, value, class: "alert alert-#{flash_class(key)} alert-dismissable" do
    %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'alert', type: 'button'} ×
    = value